---
applications:
  - name: splunk-firehose-nozzle
    memory: 512M
    instances: 2
    buildpack: go_buildpack
    cmd: splunk-firehose-nozzle
    env:
      GOPACKAGENAME: main
      API_ENDPOINT:
      API_USER:
      API_PASSWORD:
      CLIENT_ID:
      CLIENT_SECRET:
      SPLUNK_HOST:
      SPLUNK_TOKEN:
      SPLUNK_INDEX:
      SPLUNK_METRIC_INDEX:
      SKIP_SSL_VALIDATION_CF: true
      SKIP_SSL_VALIDATION_SPLUNK: true
      JOB_NAME: splunk-nozzle
      JOB_INDEX: -1
      JOB_HOST: localhost
      ADD_APP_INFO: AppName,OrgName,OrgGuid,SpaceName,SpaceGuid
      ADD_TAGS: true
      IGNORE_MISSING_APP: true
      MISSING_APP_CACHE_INVALIDATE_TTL: 3600s
      APP_CACHE_INVALIDATE_TTL: 86440s
      APP_LIMITS: 1000
      BOLTDB_PATH: cache.db
      EVENTS: ValueMetric,CounterEvent,Error,HttpStartStop,LogMessage,ContainerMetric
      EXTRA_FIELDS: name:update-ci-test
      FIREHOSE_SUBSCRIPTION_ID: splunk-ci
      FLUSH_INTERVAL: 5s
      CONSUMER_QUEUE_SIZE: 10000
      HEC_BATCH_SIZE: 1000
      HEC_RETRIES: 5
      HEC_WORKERS: 8
      DEBUG: false
      ENABLE_EVENT_TRACING: true
      STATUS_MONITOR_INTERVAL: 1s
      SELECTED_MONITORING_METRICS: nozzle.queue.percentage,splunk.events.dropped.count,splunk.events.sent.count,firehose.events.dropped.count,firehose.events.received.count,splunk.events.throughput,nozzle.usage.ram,nozzle.usage.cpu,nozzle.cache.memory.hit,nozzle.cache.remote.hit,nozzle.cache.boltdb.hit
